FROM debian:stretch

WORKDIR /build

RUN apt-get update && apt-get install -y \
    debhelper \
    dh-virtualenv \
    dh-systemd \
    git \
    python3

COPY . /build

RUN git config --global user.name "Tarjei Husøy (automated)" && git config --global user.email "apt@thusoy.com"

RUN ./tools/build_deb.sh
