FROM debian:jessie

WORKDIR /build

RUN apt-get update && apt-get install -y \
    debhelper \
    dh-virtualenv \
    dh-systemd \
    git \
    python-setuptools \
    python3 \
    python3-dev

COPY . /build

RUN git config --global user.name "Tarjei Husoy (automated)" && git config --global user.email "apt@thusoy.com"

RUN ./tools/build_deb.sh
