FROM debian:bookworm-slim

WORKDIR /build

RUN apt-get update && apt-get install -y \
    debhelper \
    dh-virtualenv \
    git \
    python3 \
    python3-venv

COPY . /build

RUN git config --global user.name "Tarjei Husøy (automated)" && git config --global user.email "apt@thusoy.com"

# Ref https://github.com/yaml/pyyaml/issues/736 to fix pyyaml build error
#RUN echo 'Cython < 3.0' > /tmp/constraint.txt && \
#   python3 -m venv /tmp/venv &&  PIP_CONSTRAINT=/tmp/constraint.txt /tmp/venv/bin/pip wheel PyYAML==5.4

RUN ./tools/build_deb.sh
